//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_DMG
    {
        public int IDCT_DMG { get; set; }
        public Nullable<int> MaDMG { get; set; }
        public Nullable<int> MaCV { get; set; }
    
        public virtual ChucVu ChucVu { get; set; }
        public virtual DMG DMG { get; set; }
    }
}
