//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DMG()
        {
            this.CT_DMG = new HashSet<CT_DMG>();
        }
    
        public int MaDMG { get; set; }
        public Nullable<int> MaGV { get; set; }
        public Nullable<int> IDNamHoc { get; set; }
        public Nullable<int> TongHeSo { get; set; }
        public Nullable<int> MaHocHam { get; set; }
        public Nullable<int> TongDMG { get; set; }
        public Nullable<bool> Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_DMG> CT_DMG { get; set; }
        public virtual GV GV { get; set; }
        public virtual HocHam HocHam { get; set; }
        public virtual NamHoc NamHoc { get; set; }
    }
}
