//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DNDoiGio
    {
        public int MaDN { get; set; }
        public Nullable<int> MaLichGD { get; set; }
        public Nullable<int> MaLichGD2 { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual LichGD LichGD { get; set; }
    }
}
