//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DNDoiGV
    {
        public int MaDN { get; set; }
        public Nullable<int> MaPCGD { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> MaGV { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> NgayBD { get; set; }
        public Nullable<System.DateTime> NgayKT { get; set; }
    
        public virtual GV GV { get; set; }
        public virtual PCGD PCGD { get; set; }
    }
}
