//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LopHP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LopHP()
        {
            this.PCGDs = new HashSet<PCGD>();
        }
    
        public int MaHP { get; set; }
        public Nullable<int> IDNamHoc { get; set; }
        public Nullable<int> SiSo { get; set; }
        public string LHDT { get; set; }
        public string DiaDiem { get; set; }
        public string Kip { get; set; }
        public Nullable<int> SoTietTKB { get; set; }
        public string TenLop { get; set; }
        public Nullable<System.DateTime> TGTHIKT { get; set; }
        public string HinhThucThi { get; set; }
        public Nullable<int> MaMH { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<double> HeSoKip { get; set; }
        public Nullable<double> HeSoLHDT { get; set; }
        public Nullable<double> HeSoQS { get; set; }
        public Nullable<double> HeSoDD { get; set; }
        public Nullable<double> TongHeSo { get; set; }
        public Nullable<int> SoTietQuyChuan { get; set; }
        public string MaHocPhan { get; set; }
    
        public virtual MonHoc MonHoc { get; set; }
        public virtual NamHoc NamHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PCGD> PCGDs { get; set; }
    }
}
