//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeachingScheduleEntities : DbContext
    {
        public TeachingScheduleEntities()
            : base("name=TeachingScheduleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BoMon> BoMons { get; set; }
        public virtual DbSet<ChucVu> ChucVus { get; set; }
        public virtual DbSet<CT_DMG> CT_DMG { get; set; }
        public virtual DbSet<DMG> DMGs { get; set; }
        public virtual DbSet<DNDoiGio> DNDoiGios { get; set; }
        public virtual DbSet<DNDoiGV> DNDoiGVs { get; set; }
        public virtual DbSet<GV> GVs { get; set; }
        public virtual DbSet<HocHam> HocHams { get; set; }
        public virtual DbSet<LichGD> LichGDs { get; set; }
        public virtual DbSet<LopHP> LopHPs { get; set; }
        public virtual DbSet<MonHoc> MonHocs { get; set; }
        public virtual DbSet<NamHoc> NamHocs { get; set; }
        public virtual DbSet<NCKH> NCKHs { get; set; }
        public virtual DbSet<PCGD> PCGDs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
