//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCKH
    {
        public int MaNCKH { get; set; }
        public Nullable<int> MaGV { get; set; }
        public string HangMuc { get; set; }
        public string NoiDung { get; set; }
        public string TaiLieu { get; set; }
        public string ThoiGian { get; set; }
        public Nullable<int> SoGioNC { get; set; }
    
        public virtual GV GV { get; set; }
    }
}
